[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && (npx tsc; true)"

[deploy]
startCommand = "npx prisma migrate deploy && npx tsx src/index.ts"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
